# Generated by Django 3.1.1 on 2020-09-10 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_venue', models.CharField(max_length=25)),
                ('event_date', models.DateField(default=None)),
                ('event_time', models.TimeField(default=None)),
                ('event_description', models.CharField(max_length=100)),
                ('event_admin', models.CharField(max_length=50)),
                ('event_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('temp_password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('payment_amount', models.CharField(max_length=5)),
                ('payment_ref', models.CharField(max_length=10)),
                ('num_guests', models.IntegerField(default=1)),
                ('num_days', models.IntegerField(default=2)),
                ('mode_of_travel', models.CharField(max_length=5)),
                ('arrival_date', models.DateField(default=None)),
                ('arrival_time', models.TimeField(default=None)),
                ('departure_date', models.DateField(default=None)),
                ('pickup', models.CharField(max_length=5)),
                ('is_deleted', models.CharField(default='No', max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='File_uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(default=None, upload_to='media/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
