# Generated by Django 3.1.1 on 2020-10-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('title', models.CharField(default=None, max_length=50)),
                ('speaker', models.CharField(default=None, max_length=50)),
                ('presenter', models.CharField(default=None, max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
